AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  sam-app

  Sample SAM Template for sam-app
  
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  
  Function:
    Environment:
      Variables:
        AWS_DYNAMODB_TABLE_NAME: aws-demo-table
        AWS_S3_BUCKET_NAME: !GetAtt SrcBucket.BucketName # resource SrcBucket does not support attribute type BucketName in Fn::GetAtt : try !ref
        #AWS_DYNAMODB_WRITER_LAMBDA_ARN: arn:aws:sns:eu-west-2:987062002191:thundra-workshop-lambda-sns-topic
        AWS_SNS_TOPIC_ARN: arn:aws:sns:eu-west-2:987062002191:thundra-workshop-lambda-sns-topic
    Timeout: 3



Resources:
  DynamoDbWriterFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: thundra-aws-workshop-demo-project/thundra-workshop-lambda-dynamodb-writer/src/
      Handler: index.handler
      Runtime: nodejs14.x
      #Events:
        #write:
          #Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          #Properties:
            #Path: /hello
            #Method: get
  SnsWriter:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: thundra-aws-workshop-demo-project/thundra-workshop-lambda-sns-writer/src/
      Handler: index.handler
      Runtime: nodejs14.x
      Policies: 
        - SNSPublishMessagePolicy:
            TopicName: '*'   ##specilizate resources
        - S3ReadPolicy:
            BucketName: '*'


  WebContentRetriever:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: thundra-aws-workshop-demo-project/thundra-workshop-lambda-webcontent-retriever/src/
      Handler: index.handler
      Runtime: nodejs14.x

  SnsTopic:
    Type: AWS::SNS::Topic
    Properties:
      DisplayName: 'thundra-workshop-lambda-sns-topic'
      TopicName: 'thundra-workshop-lambda-sns-topic'
      

  DynamoDBTable:
    Type: AWS::DynamoDB::Table
    Properties: 
      AttributeDefinitions: 
        - AttributeName: id
          AttributeType: S
      KeySchema: 
        - AttributeName: id
          KeyType: HASH
      ProvisionedThroughput: 
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
  SrcBucket:
    Type: AWS::S3::Bucket

