baseURL = 'https://thundra.io'
languageCode = 'en-us'
title = 'Thundra Foresight Workshop'
theme = 'hugo-theme-learn'

metaDataFormat = "yaml"
defaultContentLanguageInSubdir= "true"
uglyurls = "true"
enableEmoji = true

[params]
  author = "mehmetyz"
  description = "Thundra Foresight AWS Workshop"
  showVisitedLinks = false
  disableSearch = false
  disableAssetsBusting = false
  disableInlineCopyToClipBoard = false
  disableShortcutsTitle = false
  disableLanguageSwitchingButton = true
  disableBreadcrumb = false
  disableNextPrev = false
  ordersectionsby = "weight"
  themeVariant = "mine"

[outputs]
home = [ "HTML", "RSS", "JSON"]

[[menu.shortcuts]] 
name = "<i class='fas fa-graduation-cap'></i> Modernization Workshops"
url = "https://awsworkshop.io"
weight = 10

[[menu.shortcuts]]
name = "<i class='fas fa-tools'></i> AWS Builders Library"
url = "https://aws.amazon.com/builders-library/"
weight = 11

[[menu.shortcuts]]
name = "<i class='far fa-lightbulb'></i> Modernization with AWS"
url = "https://aws.amazon.com/blogs/modernizing-with-aws/"
weight = 20

[[menu.shortcuts]]
name = "<i class='fas fa-chalkboard-teacher'></i> EKS Workshop"
url = "https://eksworkshop.com/"
weight = 21

[[menu.shortcuts]]
name = "<i class='fas fa-chalkboard-teacher'></i> ECS Workshop"
url = "https://ecsworkshop.com/"
weight = 22

[[menu.shortcuts]]
name = "<i class='fas fa-chalkboard-teacher'></i> App Mesh Workshop"
url = "https://www.appmeshworkshop.com/"
weight = 23

[markup]
  defaultMarkdownHandler = "blackfriday"
  [markup.blackFriday]
    hrefTargetBlank = true