service: thundra-workshop-lambda-dynamodb-writer

frameworkVersion: '2 || 3'

custom:
  DYNAMODB_TABLE_NAME: test-table
  AWS_REGION: 'eu-west-1'

provider:
  name: aws
  runtime: nodejs12.x
  region: ${self:custom.AWS_REGION}
  lambdaHashingVersion: 20201221

  environment:
    AWS_DYNAMODB_TABLE_NAME: ${self:custom.DYNAMODB_TABLE_NAME}
    
  iam:
    role:
      name: thundra-workshop-lambda-dynamodb-writer-role
      statements:
        - Effect: Allow
          Action:
            - dynamodb:PutItem
            - dynamodb:UpdateItem

          Resource: "*"
functions:
  writer:
    handler: src/index.handler
    memorySize: 128
    timeout: 60
